// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  $(document).ready(function() {
    var clearInfo, place;
    place = $("#solition");
    $("#btn-solve").click(function() {
      console.log("Click!");
      return $.ajax({
        url: "/",
        data: $("#ExpressionForm").serialize(),
        type: 'POST',
        success: function(response) {
          var result, s;
          console.log(response);
          result = $.parseJSON(response);
          clearInfo();
          console.log(result);
          if (result.IsSuccess) {
            s = result.Solution;
            console.log(s);
          } else {
            s = "<div class=\"error-message alert alert-dismissable alert-danger\">";
            s += result.ErrorMessage;
            s += "</div>";
          }
          return $("#solution").append(s);
        }
      });
    });
    return clearInfo = function() {
      return $("#solution").empty();
    };
  });

}).call(this);
